name: "Hello world workflow"

on:
  push:
    branches:
      - master
      - main
      - production

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"
