name: "Multi event pipeline / workflow"

on:
    push: # Event: Whenever  a push is made to the repository on the master branch
        branches:
            - master
            - test

    pull_request:
        branches:
            - master 

jobs:
    on-push: # job name
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master push" # Step no 1
              run: echo "Running on master push"

    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu -latest
        steps: # Steps to be executed in the job
            - name: "Running on pull request" # Step no 1
              run: echo "Running on pull request"

    